version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.1-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            gem install bundler -v 2.1.4
            bundle install
            git checkout production
            git merge main --no-ff
            bundle exec ruby build/build.rb
            echo $(date) > build_timestamp
            git add --all
            git commit -m "Build $(date)"
            git push origin production

workflows:
  version: 2
  deploy:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "5 3,11,15 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build
